theme = "terminal"
baseURL = "https://phdpersonalpagetutorial.netlify.app/"




buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10


[taxonomies]
  tag = "tags"
  category = "categories"

[markup.highlight]
  noClasses = false