languageCode = "en"
languageName = "English"
weight = 1
title = "Dmitry Muravyov"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Dmitry Muravyov's website"

[params.author]
  name = "Dmitry Muravyov"
  email = "d.v.muravev@tudelft.nl"
  headline = "PhD Candidate at TU Delft"
  bio = "I am an interdisciplinary researcher interested in philosophy (of technology), science & technology studies, and design research"
  links = [
    { google-scholar = "https://scholar.google.com/citations?user=H-pBe1kAAAAJ&hl=en" },
    { linkedin = "https://www.linkedin.com/in/dmitry-muravyov-28270b2a4/" },
    { email = "mailto:r.huffington-smythe@university.edu" },
  ]
  image = "img/my-photo.png"