colorScheme = "bloody"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["research", "publications"]

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  cardView = false

[article]
  showDate = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  showReadingTime = false
  showWordCount = false
  showTableOfContents = true

[list]
  showCards = false
  showBreadcrumbs = true
  showTableOfContents = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
