[params]
  # "posts" = content shown on homepage. Change if you want a different section on homepage.
  contentTypeName = "posts"
  showMenuItems = 4
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  readingTime = true
  Toc = true
  TocTitle = "Table of Contents"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    title = "Dmitry Muravyov's website"
    languageName = "English"

    [languages.en.params]
      subtitle = "Personal website"
      owner = "Dmitry Muravyov"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Your Site"
        logoHomeLink = "/"

      [[languages.en.menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 1