[params]
  contentTypeName = "posts"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  readingTime = true
  Toc = true
  TocTitle = "Table of Contents"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    title = "Dmitry Muravyov"

    [languages.en.params]
      subtitle = "PhD Candidate at TU Delft"
      owner = "Dmitry Muravyov"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "D.M."
        logoHomeLink = "/"

      [languages.en.params.author]
        name = "Dmitry Muravyov"
        email = "d.v.muravev@tudelft.nl"
        headline = "PhD Candidate at TU Delft"
        bio = "Interdisciplinary researcher in philosophy of technology, STS, and design research"
        links = [
          { google-scholar = "https://scholar.google.com/citations?user=H-pBe1kAAAAJ&hl=en" },
          { linkedin = "https://www.linkedin.com/in/dmitry-muravyov-28270b2a4/" },
          { email = "mailto:d.v.muravev@tudelft.nl" },
        ]
        image = "img/my-photo.png"
